name: Test Formula

on:
  push:
    branches: [main]
    paths:
      - "Formula/**"
  pull_request:
    branches: [main]
    paths:
      - "Formula/**"

jobs:
  test-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          brew update

      - name: Install Formula
        run: |
          # Install the formula
          brew install --build-from-source ./Formula/languagetool-obsidian.rb

          # Verify installation
          if [ -f "$(brew --prefix)/bin/languagetool-obsidian-server" ]; then
            echo "✅ Server binary installed correctly"
          else
            echo "❌ Server binary not found"
            exit 1
          fi

      - name: Verify Server Binary
        run: |
          # Check if the binary exists and is executable
          if [ -x "$(brew --prefix)/bin/languagetool-obsidian-server" ]; then
            echo "✅ Server binary is executable"
          else
            echo "❌ Server binary is not executable"
            exit 1
          fi

          # Check the contents of the script
          if grep -q "languagetool-server.jar" "$(brew --prefix)/bin/languagetool-obsidian-server"; then
            echo "✅ Server binary contains correct paths"
          else
            echo "❌ Server binary doesn't contain expected content"
            exit 1
          fi

      - name: Verify Service Setup
        run: |
          # Check if the service can be loaded
          brew services start languagetool-obsidian || { echo "❌ Failed to start service"; exit 1; }
          echo "✅ Service started successfully"

          # Wait a moment for the service to initialize
          sleep 5

          # Check if the service appears in the list
          if brew services list | grep -q languagetool-obsidian; then
            echo "✅ Service is listed in brew services"
          else
            echo "❌ Service is not listed in brew services"
            exit 1
          fi

          # Stop the service
          brew services stop languagetool-obsidian

      - name: Uninstall Formula
        if: always()
        run: |
          brew services stop languagetool-obsidian || true
          brew uninstall languagetool-obsidian || true
