name: Test Formula

on:
  push:
    branches: [main]
    paths:
      - "Formula/**"
  pull_request:
    branches: [main]
    paths:
      - "Formula/**"

jobs:
  test-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          brew update

      - name: Install Formula
        run: |
          # Install the formula
          brew install --build-from-source ./Formula/languagetool-obsidian.rb

          # Verify installation
          if [ -f "$(brew --prefix)/bin/languagetool-obsidian-server" ]; then
            echo "✅ Server binary installed correctly"
          else
            echo "❌ Server binary not found"
            exit 1
          fi

      - name: Verify Server Binary
        run: |
          # Test the server binary with --help (should not start the server)
          if "$(brew --prefix)/bin/languagetool-obsidian-server" --help 2>&1 | grep -q "HTTPServer"; then
            echo "✅ Server binary is working properly"
          else
            echo "❌ Server binary failed to run"
            exit 1
          fi

      - name: Uninstall Formula
        run: |
          brew uninstall languagetool-obsidian
